apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gosqlguard.fullname" . }}
  labels:
    {{- include "gosqlguard.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gosqlguard.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gosqlguard.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gosqlguard.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.settings.debug }}
            - name: DEBUG
              value: "true"
            {{- end }}
            # Metadata database configuration
            - name: METADATA_DB_ENABLED
              value: {{ .Values.settings.metadata_database.enabled | quote }}
            - name: METADATA_DB_HOST
              value: {{ .Values.settings.metadata_database.host | quote }}
            - name: METADATA_DB_PORT
              value: {{ .Values.settings.metadata_database.port | quote }}
            - name: METADATA_DB_USERNAME
              value: {{ .Values.settings.metadata_database.username | quote }}
            - name: METADATA_DB_PASSWORD
              value: {{ .Values.settings.metadata_database.password | quote }}
            - name: METADATA_DB_DATABASE
              value: {{ .Values.settings.metadata_database.database | quote }}
            - name: METADATA_DB_MAX_OPEN_CONNS
              value: {{ .Values.settings.metadata_database.maxOpenConns | quote }}
            - name: METADATA_DB_MAX_IDLE_CONNS
              value: {{ .Values.settings.metadata_database.maxIdleConns | quote }}
            - name: METADATA_DB_CONN_MAX_LIFETIME
              value: {{ .Values.settings.metadata_database.connMaxLifetime | quote }}
            - name: METADATA_DB_AUTO_MIGRATE
              value: {{ .Values.settings.metadata_database.autoMigrate | quote }}
            # Local storage configuration
            - name: LOCAL_BACKUP_ENABLED
              value: {{ .Values.settings.local.enabled | quote }}
            - name: LOCAL_BACKUP_DIRECTORY
              value: {{ .Values.settings.local.backupDirectory | quote }}
            {{- if hasKey .Values.settings.local "organizationStrategy" }}
            - name: LOCAL_ORGANIZATION_STRATEGY
              value: {{ .Values.settings.local.organizationStrategy | quote }}
            {{- end }}
            # S3 storage configuration
            - name: S3_BACKUP_ENABLED
              value: {{ .Values.settings.s3.enabled | quote }}
            - name: S3_BUCKET
              value: {{ .Values.settings.s3.bucket | quote }}
            - name: S3_REGION
              value: {{ .Values.settings.s3.region | quote }}
            - name: S3_ENDPOINT
              value: {{ .Values.settings.s3.endpoint | quote }}
            - name: S3_ACCESS_KEY
              value: {{ .Values.settings.s3.accessKey | quote }}
            - name: S3_SECRET_KEY
              value: {{ .Values.settings.s3.secretKey | quote }}
            {{- if hasKey .Values.settings.s3 "prefix" }}
            - name: S3_PREFIX
              value: {{ .Values.settings.s3.prefix | quote }}
            {{- end }}
            - name: S3_USE_SSL
              value: {{ .Values.settings.s3.useSSL | quote }}
            {{- if hasKey .Values.settings.s3 "skipCertValidation" }}
            - name: S3_SKIP_CERT_VALIDATION
              value: {{ .Values.settings.s3.skipCertValidation | quote }}
            {{- end }}
            {{- if hasKey .Values.settings.s3 "organizationStrategy" }}
            - name: S3_ORGANIZATION_STRATEGY
              value: {{ .Values.settings.s3.organizationStrategy | quote }}
            {{- end }}
            # Metrics configuration
            - name: METRICS_PORT
              value: {{ .Values.settings.metrics.port | quote }}
            # Support custom S3 endpoint regions
            - name: AWS_IGNORE_CONFIGURED_ENDPOINT_URLS
              value: "true"
            - name: AWS_S3_FORCE_PATH_STYLE
              value: "true"
          ports:
            - name: http
              containerPort: {{ .Values.service.adminUIPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: backup-volume
              mountPath: {{ .Values.settings.local.backupDirectory }}
            {{- end }}
            {{- if .Values.metadataPersistence.enabled }}
            - name: metadata-volume
              mountPath: /app/metadata
            {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: backup-volume
          persistentVolumeClaim:
            claimName: {{ include "gosqlguard.backupVolumeName" . }}
        {{- end }}
        {{- if .Values.metadataPersistence.enabled }}
        - name: metadata-volume
          persistentVolumeClaim:
            claimName: {{ include "gosqlguard.metadataVolumeName" . }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
