apiVersion: v1
kind: Service
metadata:
  name: {{ include "gosqlguard.fullname" . }}
  labels:
    {{- include "gosqlguard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.adminUIPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gosqlguard.selectorLabels" . | nindent 4 }}
